# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test" << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false
end

desc "Print the default configuration this gem injects into RuboCop"
task :config do
  require "yaml"
  puts File.read(File.expand_path("config/default.yml", __dir__))
end

task default: :test
